apiVersion: v1
kind: Pod
metadata:
  name: curl
  labels:
    app: curl
  annotations:
    sidecar.istio.io/inject: "false"
spec:
  containers:
  - image: radial/busyboxplus:curl
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: curl
  restartPolicy: Always
