#for external access to minikube
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dev
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dev-minikube-access
rules:
  -
    apiGroups:
      - ""
      - apps
      - autoscaling
      - batch
      - extensions
      - policy
      - rbac.authorization.k8s.io
    resources:
      - replicasets
      - serviceaccounts
      - secrets
      - pods
      - services
      - configmaps
      - namespaces
      - deployments
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dev-minikube-access
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dev-minikube-access
subjects:
- kind: ServiceAccount
  name: dev
  namespace: default
