version: 0.0
os: linux
files:
  - source: /package.json
    destination: /home/ec2-user/app
  - source: /securityApp.js
    destination: /home/ec2-user/app
  - source: /config
    destination: /home/ec2-user/app/config
  - source: /protos
    destination: /home/ec2-user/app/protos
  - source: /cert
    destination: /home/ec2-user/app/cert
  - source: /swagger.yaml
    destination: /home/ec2-user/app
  - source: /pm2.config.js
    destination: /home/ec2-user/app
permissions:
  - object: /home/ec2-user
    pattern: "app"
    owner: ec2-user
    group: ec2-user
    type:
      - directory
  - object: /home/ec2-user/app
    pattern: "**"
    owner: ec2-user
    group: ec2-user
hooks:
  AfterInstall:
    - location: scripts/install_packages.sh
      timeout: 3500
      runas: ec2-user
    - location: scripts/start_server.sh
      timeout: 300
      runas: ec2-user
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: ec2-user

