FROM node:8

WORKDIR /var/www

# Install app dependencies
COPY ./dist/package*.json ./

RUN npm install --production

COPY ./dist/securityApp.js .

ENV DEBUG=app:*

EXPOSE 3001
CMD [ "npm", "run", "serve" ]