FROM node:8

WORKDIR /var/www

# Install app dependencies
COPY ./package*.json /var/www/

RUN npm install migrate-mongo cross-env dotenv

COPY . .

ENV DEBUG=app:* NODE_ENV=development NODE_CONFIG_DIR=./src/config
