FROM node:10.16.0-alpine

WORKDIR /var/www

# Install app dependencies
COPY ./dist/package*.json ./

RUN npm install --production

COPY ./dist/securityApp.js .

# this will be overrided by kubernetes configmap
COPY ./dist/config/production.js ./config/production.js

COPY ./dist/protos ./protos

COPY ./dist/cert ./cert

COPY ./dist/swagger.yaml ./swagger.yaml

ENV DEBUG=app:* NODE_ENV=production

EXPOSE 3001
CMD [ "npm", "run", "serve" ]
