FROM node:alpine3.15

WORKDIR /var/www

# Install app dependencies
COPY ./migrations.package.json /var/www/package.json

RUN npm install

COPY ./migrate-mongo-config.js ./.env ./
COPY ./migrations ./migrations

ENV DEBUG=app:* NODE_ENV=development NODE_CONFIG_DIR=./src/config
