apiVersion: v1
kind: Pod
spec:
  nodeSelector:
    kubernetes.io/hostname: k8s-node3
  volumes:
  - name: sock-volume
    hostPath:
      path: /var/run/docker.sock
  containers:
  - name: git
    imagePullPolicy: IfNotPresent
    image: alpine/git
    command: ["sh", "-c", "sleep infinity"]
  - name: yq
    imagePullPolicy: IfNotPresent
    image: mikefarah/yq
    command: ["sh", "-c", "sleep infinity"]
  - name: shell
    imagePullPolicy: IfNotPresent
    image: alpinelinux/docker-cli
    volumeMounts:
      - name: sock-volume
        mountPath: /var/run/docker.sock
    command:
    - sleep
    args:
    - infinity
