apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
    - image: security-app
      docker:
        dockerfile: Dockerfile-dev
  local:
    push: false
deploy:
  kubectl:
    manifests:
      - k8s/init/*.yaml
      - k8s/db/*.yaml
      - k8s/*.yaml
