apiVersion: v1
kind: Service
metadata:
  name: security-db
  namespace: default
  labels:
    app: security-db
spec:
  clusterIP: None
  selector:
    app: security-db
  ports:
  - name: mongo
    protocol: TCP
    port: 27017
    targetPort: 27017
