apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: restaurant
spec:
  hosts:
  - "*"
  gateways:
  - bookinfo-gateway
  http:
  - match:
    - uri:
        prefix: /securityApi/
    - uri:
        prefix: /securityApi
    rewrite:
      uri: "/"
    route:
    - destination:
        host: security-app
        port:
          number: 3001
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: security-app
spec:
  hosts:
  - security-app
  http:
  - route:
    - destination:
        host: security-app
        subset: v1
