apiVersion: v1
kind: Secret
metadata:
  name: security-app
  namespace: default
  labels:
    app: security
type: Opaque
stringData:
  dbUserName: "security_user"
  dbPassword: "1234"
  dbAccessTokenSecret: "Th1s1sth3endBeatuf@friend18237_+as"
  dbRefreshTokenSecret: "Th1s1sth3endBeatuf@friend121234_xcvf%"
