kind: Service
apiVersion: v1
metadata:
  name: security-app
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: security
  ports:
  - protocol: TCP
    port: 3001
    targetPort: 3001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: security-app
spec:
  selector:
    matchLabels:
      app: security
  replicas: 1
  template:
    metadata:
      labels:
        app: security
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
      - name: res-security
        image: security-app
        ports:
        - containerPort: 3001
        env:
          - name: SECURITY_DB_USER
            valueFrom:
              secretKeyRef:
                name: security-app
                key: dbUserName
          - name: SECURITY_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: security-app
                key: dbPassword
          - name: SECURITY_ACCESS_TOKEN_SECRET
            valueFrom:
              secretKeyRef:
                name: security-app
                key: dbAccessTokenSecret
          - name: SECURITY_REFRESH_TOKEN_SECRET
            valueFrom:
              secretKeyRef:
                name: security-app
                key: dbRefreshTokenSecret
